### PR TITLE
Add ScopeFactory API

### PR DESCRIPTION
**Pull request by Leland-Takamine**
See #108 for details. This PR adds the `ScopeFactory` API alongside the existing `@Dependencies` API. If `ScopeFactory` proves to be a better alternative, we will remove `@Dependencies` in a subsequence change.

### CODE REVIEW

**Comment by Leland-Takamine** [comment]
I've removed the tests for now for easier code review. I'll add back before landing.

**Comment by andreasnomikos** [comment]
make sure to add appropriate proguard configuration for the reflection

**Comment by Leland-Takamine** [comment]
> make sure to add appropriate proguard configuration for the reflection

Good point will do.

**Comment by Leland-Takamine** [comment]
Just an update on this PR. There are some API issues that need to be thought through and resolved before landing this (if at all). Namely, `@Dependencies` can "hide" `@Exposed` dependencies provided by parents. It doesn't make sense for `ScopeFactory` to do the same since the factory definition is decoupled from the Scope definition.

**Comment by Leland-Takamine** [comment]
Abandoning in favor of #125.

**Pull request closed without merging**
